/**
 * Pakistani cities, for the patient log's City picker.
 *
 * A fixed on-device list rather than an API call: the app has to work with no
 * signal, and this data never changes between releases. It is deliberately
 * broad — reps cover small towns, and a city missing from the list would be a
 * city a patient can't be filed under.
 *
 * Ordered by province so the picker reads sensibly when scrolled, though the
 * sheet's search is how it is normally used. `PAKISTAN_CITIES` is the flat,
 * alphabetically sorted list the picker consumes.
 */

/** Sindh */
const SINDH = [
  'Karachi',
  'Hyderabad',
  'Sukkur',
  'Larkana',
  'Nawabshah',
  'Mirpur Khas',
  'Shikarpur',
  'Jacobabad',
  'Khairpur',
  'Dadu',
  'Tando Adam',
  'Tando Allahyar',
  'Badin',
  'Thatta',
  'Ghotki',
  'Kandhkot',
  'Sanghar',
  'Umerkot',
  'Kashmore',
  'Matiari',
  'Naushahro Feroze',
  'Tharparkar',
  'Jamshoro',
  'Sujawal',
  'Kotri',
  'Rohri',
  'Moro',
  'Pano Aqil',
];

/** Punjab */
const PUNJAB = [
  'Lahore',
  'Faisalabad',
  'Rawalpindi',
  'Multan',
  'Gujranwala',
  'Sialkot',
  'Bahawalpur',
  'Sargodha',
  'Sheikhupura',
  'Jhang',
  'Rahim Yar Khan',
  'Gujrat',
  'Kasur',
  'Sahiwal',
  'Okara',
  'Wah Cantonment',
  'Dera Ghazi Khan',
  'Chiniot',
  'Kamoke',
  'Mandi Bahauddin',
  'Jhelum',
  'Khanewal',
  'Muzaffargarh',
  'Vehari',
  'Attock',
  'Chakwal',
  'Bahawalnagar',
  'Toba Tek Singh',
  'Layyah',
  'Rajanpur',
  'Pakpattan',
  'Lodhran',
  'Hafizabad',
  'Narowal',
  'Mianwali',
  'Bhakkar',
  'Khushab',
  'Nankana Sahib',
  'Burewala',
  'Daska',
  'Gojra',
  'Kot Addu',
  'Wazirabad',
  'Jaranwala',
  'Chishtian',
  'Muridke',
  'Hasilpur',
  'Arifwala',
  'Mian Channu',
  'Kabirwala',
  'Shorkot',
  'Kharian',
  'Sambrial',
  'Shakargarh',
  'Talagang',
  'Pindi Bhattian',
  'Sadiqabad',
  'Ahmadpur East',
  'Khanpur',
  'Liaquatpur',
  'Murree',
  'Taxila',
  'Kahuta',
  'Depalpur',
  'Renala Khurd',
  'Haroonabad',
  'Fort Abbas',
  'Jalalpur Jattan',
  'Pasrur',
  'Sarai Alamgir',
  'Dinga',
  'Malakwal',
  'Phalia',
  'Bhalwal',
  'Kot Momin',
  'Shahkot',
  'Sillanwali',
  'Chunian',
  'Pattoki',
  'Raiwind',
  'Jampur',
  'Taunsa',
  'Alipur',
  'Jatoi',
  'Karor Lal Esan',
  'Choa Saidan Shah',
  'Pind Dadan Khan',
  'Dina',
  'Gujar Khan',
  'Jhelum Cantt',
];

/** Khyber Pakhtunkhwa */
const KPK = [
  'Peshawar',
  'Mardan',
  'Mingora',
  'Kohat',
  'Abbottabad',
  'Dera Ismail Khan',
  'Nowshera',
  'Swabi',
  'Charsadda',
  'Mansehra',
  'Haripur',
  'Bannu',
  'Batkhela',
  'Timergara',
  'Hangu',
  'Karak',
  'Lakki Marwat',
  'Tank',
  'Chitral',
  'Dir',
  'Swat',
  'Buner',
  'Shangla',
  'Malakand',
  'Battagram',
  'Torghar',
  'Upper Kohistan',
  'Lower Kohistan',
  'Khyber',
  'Bajaur',
  'Mohmand',
  'Kurram',
  'Orakzai',
  'North Waziristan',
  'South Waziristan',
  'Havelian',
  'Topi',
  'Risalpur',
  'Takht Bhai',
  'Jamrud',
];

/** Balochistan */
const BALOCHISTAN = [
  'Quetta',
  'Turbat',
  'Khuzdar',
  'Chaman',
  'Hub',
  'Gwadar',
  'Sibi',
  'Zhob',
  'Loralai',
  'Dera Murad Jamali',
  'Dera Allah Yar',
  'Usta Muhammad',
  'Mastung',
  'Kalat',
  'Pishin',
  'Nushki',
  'Kharan',
  'Panjgur',
  'Lasbela',
  'Jaffarabad',
  'Naseerabad',
  'Sohbatpur',
  'Jhal Magsi',
  'Bolan',
  'Ziarat',
  'Killa Abdullah',
  'Killa Saifullah',
  'Barkhan',
  'Musakhel',
  'Sherani',
  'Awaran',
  'Washuk',
  'Chagai',
  'Harnai',
  'Duki',
  'Kohlu',
  'Dera Bugti',
];

/** Islamabad, Azad Jammu & Kashmir, and Gilgit-Baltistan */
const FEDERAL_AND_NORTH = [
  'Islamabad',
  'Muzaffarabad',
  'Mirpur',
  'Kotli',
  'Bhimber',
  'Rawalakot',
  'Bagh',
  'Poonch',
  'Neelum',
  'Haveli',
  'Sudhnoti',
  'Gilgit',
  'Skardu',
  'Hunza',
  'Nagar',
  'Ghizer',
  'Astore',
  'Diamer',
  'Ghanche',
  'Shigar',
  'Kharmang',
  'Chilas',
];

/**
 * Every city, de-duplicated and alphabetically sorted — the order the picker
 * shows them in. Sorted once at module load rather than on every render.
 */
export const PAKISTAN_CITIES: string[] = [
  ...new Set([
    ...SINDH,
    ...PUNJAB,
    ...KPK,
    ...BALOCHISTAN,
    ...FEDERAL_AND_NORTH,
  ]),
].sort((left, right) => left.localeCompare(right));
